// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSBQJ95fPhGsAt4EbxAH8lmtqRfpf-P08',
    appId: '1:457450586249:web:cbba8c41621a914212c658',
    messagingSenderId: '457450586249',
    projectId: 'climatrip-8d3bf',
    authDomain: 'climatrip-8d3bf.firebaseapp.com',
    storageBucket: 'climatrip-8d3bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp4-rhv4u_IvlyUASAgkcweFKBNZvrvAM',
    appId: '1:457450586249:android:db21f64136a64dec12c658',
    messagingSenderId: '457450586249',
    projectId: 'climatrip-8d3bf',
    storageBucket: 'climatrip-8d3bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6vnhY7LjG4BeIB6iRYehtsYWOc-9Ykzk',
    appId: '1:457450586249:ios:de7f22e3412a0d6012c658',
    messagingSenderId: '457450586249',
    projectId: 'climatrip-8d3bf',
    storageBucket: 'climatrip-8d3bf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6vnhY7LjG4BeIB6iRYehtsYWOc-9Ykzk',
    appId: '1:457450586249:ios:de7f22e3412a0d6012c658',
    messagingSenderId: '457450586249',
    projectId: 'climatrip-8d3bf',
    storageBucket: 'climatrip-8d3bf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSBQJ95fPhGsAt4EbxAH8lmtqRfpf-P08',
    appId: '1:457450586249:web:bdf340994afbe8a312c658',
    messagingSenderId: '457450586249',
    projectId: 'climatrip-8d3bf',
    authDomain: 'climatrip-8d3bf.firebaseapp.com',
    storageBucket: 'climatrip-8d3bf.firebasestorage.app',
  );
}
